Regridding to larger grid results in NaNs outside of data range
EXCITED-CO2/xarray-regrid pull request #33
Opened 2024-02-23 16:09 UTC by kjdoore

Fixes the issue where regridding to larger grid did not result in NaNs at locations where there was no starting data. Uses a mask after regridding to fill along each coordinate with the NaNs.

2024-02-27 14:05 UTC, BSchilperoort requested changes
Thanks for making this PR!

I see that the linter check fails. You can fix the formatting by running ruff's formatter:
`ruff format .`

Could you add some tests to confirm the code works as intended? (and is not accidentally broken by others in the future)

2024-02-28 08:01 UTC, BSchilperoort approved these changes
Thanks for making the changes and adding the test!

After updating the changelog, feel free to merge this PR. I think you should be able to now. It's probably best to use the "squash and merge" option.

2024-02-28 16:20 UTC, kjdoore commented on src/xarray_regrid/methods/conservative.py
> +        )
I agree with this. Your suggestion is what I originally had, but `ruff` switched it back after formatting. Do you think we should use our preferred format or do as `ruff` suggests?

2024-02-29 06:58 UTC, BSchilperoort commented on src/xarray_regrid/methods/conservative.py
> +        )
Oh odd. Well it's best to keep it formatted, despite it being a bit ugly.

Alternatively you could use the `np.bitwise_and` function:

```py
uncovered_target_grid = np.bitwise_and(
    coords[coord] <= data[coord].max(), coords[coord] >= data[coord].min()
)
```

But I think this is acceptable.

2024-02-29 06:59 UTC, BSchilperoort approved these changes

2024-02-29 06:59 UTC, merged